### ISSUE TITLE
Todo:

### ISSUE THREAD

**Issue by ymhr** [ymhr/cdac-league#2]
- [ ] 3 leagues - senior, novice, beginner
- [ ] On the dogs record, we need to know what height they are, what grade they started at, and the dogs name.
- [ ] Points are based on different categories, based on whether independent, KC or UKA.
- [ ] When adding a run, need a way to specify if the dog 'won out' there as they get an extra 10 points.
- [ ] Clear round checkbox, may not get points for non-clear rounds.
- [ ] A way for admins to be able to add runs for another dog
- [ ] Disclaimer - this league also uses a paper version, so this website may not be accurate - if you want to submit by paper, you can.
- [ ] Option for admin to be able to specify that a dog is not eligible to win, but they can still log points/see them selves in the table, but they must be listed as such, perhaps `N/A` instead of a placing.
